services:
  plugfs:
    image: amsterdam/plugfs
    build:
      context: .
    volumes:
      - ".:/opt/plugfs"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000
    ports:
      - "10000:10000"
